import {FEATURES,CATEGORIES,SYNERGIES,ARCHETYPES} from './features.js';
import {getValue,setValue,getAllState,replaceState,storageEstimate} from './modules/storage.js';
import {detectCapabilities,runSelfTests} from './modules/capabilities.js';
import {CHAIN_STAGES,buildPrompt,stagePrompt} from './modules/prompts.js';
import {loadCatalog,initEngine,unloadEngine,generate,stopGeneration,engineInfo,getWebLLMVersion} from './modules/webllm.js';
import {joinP2PRoom,sendP2P,leaveP2PRoom,isJoined} from './modules/p2p.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={selected:new Set(),theme:'dark',reduceMotion:false,route:'overview',caps:[],peers:new Set(),prompt:'',settings:{}};
const ROUTES=[
  ['overview','Overview','⌂'],['library','Feature Library','◇'],['fusion','Fusion Lab','✣'],['prompt','Prompt Foundry','⌘'],['ai','WebLLM Lab','✦'],['multiplayer','Multiplayer','⇄'],['capabilities','Capabilities','◉'],['architecture','Architecture','▦'],['guides','Guides','?'],['integrity','Integrity','✓']
];
const PRESETS={
 multiplayer:['CRDTs','WebRTC DataChannels','Trystero peer discovery','WebSockets','Transport abstraction','Late-join snapshots','Presence service','Authoritative room state','Object-level ACLs','Report/block/mute','Contribution ledger','Universal event envelope','PWA','Offline mutation queue'],
 agentic:['WebLLM','Local RAG','AI tool calling','Agent planner/executor/verifier','AI provenance','Meta-prompt chain','Tool-scoped agents','Human-in-the-loop approval','Knowledge graph','Claim-evidence linking','Hybrid retrieval','Workflow templates','Capability registry'],
 field:['IndexedDB','OPFS','Offline mutation queue','GeoJSON layers','Offline map packs','Geolocation','Local image compression','Portable workspace bundles','Background Sync','Freshness indicators','Progressive enhancement','Zero-Harm / Anti-Inversion'],
 learning:['Quest engine','Skill trees','Team XP','Achievement provenance','Just-in-time primers','Competency pathways','Mentor matching','Adaptive explanations','Reduced motion','Caption/transcript support','Translation dictionaries','AI provenance'],
 institution:['Passkeys/WebAuthn','RBAC','Object-level ACLs','Versioned proposals','Human approval gates','Claim-evidence linking','Data lineage graph','OpenTelemetry server tracing','Signed webhooks','Stateful room objects','Relational database','Audit system']
};

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2800)}
function escapeHTML(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function download(name,text,type='text/plain'){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function featureByName(name){return FEATURES.find(f=>f.name===name)}
function selectedFeatures(){return FEATURES.filter(f=>state.selected.has(f.id))}
function persistSelections(){setValue('selectedFeatures',[...state.selected]);renderSelectedDependent()}

async function init(){
  const saved=await getValue('selectedFeatures',[]);saved.forEach(id=>state.selected.add(id));
  state.theme=await getValue('theme',localStorage.getItem('fusion-theme')||'dark');state.reduceMotion=await getValue('reduceMotion',false);
  document.documentElement.dataset.theme=state.theme;document.documentElement.classList.toggle('reduce-motion',state.reduceMotion);
  buildNav();buildFilters();buildChainOptions();renderFeatures();renderGuides();renderArchitecture();drawConstellation();
  await refreshCapabilities();await updateStatePreview();bindEvents();route();updateConnectivity();renderSelectedDependent();
  window.addEventListener('hashchange',route);window.addEventListener('online',updateConnectivity);window.addEventListener('offline',updateConnectivity);
  if('serviceWorker' in navigator && location.protocol!=='file:') navigator.serviceWorker.register('./sw.js').then(()=>$('#pwa-label').textContent='PWA service worker registered').catch(e=>$('#pwa-label').textContent=`PWA registration failed: ${e.message}`);
  else $('#pwa-label').textContent=location.protocol==='file:'?'PWA requires HTTP(S), not file://':'Service Worker unavailable';
  initSplash();
}

function initSplash(){
  const skip=localStorage.getItem('fusion-skip-splash')==='1';if(skip){$('#splash').classList.add('hidden');return}
  let p=8;const bar=$('#splash-progress'),txt=$('#splash-status');const msgs=['Loading feature ontology…','Linking capability synergies…','Preparing prompt chain…','Checking browser capabilities…','Workspace ready.'];
  const timer=setInterval(()=>{p=Math.min(96,p+Math.ceil(Math.random()*10));bar.style.width=p+'%';txt.textContent=msgs[Math.min(msgs.length-1,Math.floor(p/22))];if(p>=96)clearInterval(timer)},220);
  $('#enter-app').onclick=()=>{bar.style.width='100%';if($('#skip-splash').checked)localStorage.setItem('fusion-skip-splash','1');$('#splash').classList.add('hidden');$('#workspace').focus()};
}

function buildNav(){
  const links=ROUTES.map(([id,label,icon])=>`<a href="#${id}" data-nav="${id}">${icon} <span>${label}</span></a>`).join('');
  $('#side-nav').innerHTML=links;$('#top-nav').innerHTML=ROUTES.slice(0,6).map(([id,label])=>`<a href="#${id}" data-nav="${id}">${label}</a>`).join('');
}
function route(){let id=(location.hash||'#overview').slice(1);if(!ROUTES.some(r=>r[0]===id))id='overview';state.route=id;$$('.route').forEach(r=>r.classList.toggle('active',r.dataset.route===id));$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===id));const label=ROUTES.find(r=>r[0]===id)?.[1]||id;$('#breadcrumbs').textContent=`Foundry / ${label}`;document.title=`${label} · Feature Fusion Foundry`;$('#side').classList.remove('open');$('#drawer-toggle').setAttribute('aria-expanded','false');window.scrollTo({top:0,behavior:state.reduceMotion?'auto':'smooth'});if(id==='integrity')updateStatePreview()}

function buildFilters(){const select=$('#category-filter');CATEGORIES.forEach(c=>select.insertAdjacentHTML('beforeend',`<option value="${c.id}">${escapeHTML(c.title)}</option>`))}
function featureMatches(f){const q=$('#feature-search').value.trim().toLowerCase(),cat=$('#category-filter').value,mat=$('#maturity-filter').value,sel=$('#selected-only').checked;const hay=[f.name,f.summary,f.advanced,f.example,f.categoryTitle,...f.tags,...f.useCases].join(' ').toLowerCase();return(!q||hay.includes(q))&&(cat==='all'||f.category===cat)&&(mat==='all'||f.maturity===mat)&&(!sel||state.selected.has(f.id))}
function renderFeatures(){const visible=FEATURES.filter(featureMatches);$('#visible-count').textContent=visible.length;$('#feature-list').innerHTML=visible.map(f=>`<article class="feature-card ${state.selected.has(f.id)?'selected':''}" data-feature="${f.id}"><span class="maturity ${f.maturity}">${f.maturity}</span><div class="feature-head"><input class="feature-select" type="checkbox" ${state.selected.has(f.id)?'checked':''} aria-label="Select ${escapeHTML(f.name)}"><div><h3>${escapeHTML(f.name)} <span class="tip" tabindex="0" data-tip="${escapeHTML(f.tooltip)}">?</span></h3><div class="summary">${escapeHTML(f.summary)}</div><div class="tag-row">${f.tags.slice(0,5).map(t=>`<span class="tag">${escapeHTML(t)}</span>`).join('')}</div></div></div><details><summary>Simplified advanced description, example & use cases</summary><div class="feature-detail-grid"><div><strong>Advanced</strong>${escapeHTML(f.advanced)}</div><div><strong>Example</strong>${escapeHTML(f.example)}</div><div><strong>Recommended use</strong>${f.useCases.map(escapeHTML).join(', ')}</div><div><strong>Fusion hint</strong>${escapeHTML(f.categoryTitle)} capabilities work best when connected through explicit events, schemas and fallbacks.</div></div></details></article>`).join('')||'<div class="panel">No features match these filters.</div>';
  $$('.feature-select').forEach(box=>box.addEventListener('change',e=>{const card=e.target.closest('[data-feature]');const id=card.dataset.feature;e.target.checked?state.selected.add(id):state.selected.delete(id);card.classList.toggle('selected',e.target.checked);persistSelections()}));
}

function renderSelectedDependent(){const selected=selectedFeatures();$('#selected-count').textContent=selected.length;renderFusion(selected);updateOverviewStats();if(state.prompt)$('#prompt-metrics').innerHTML=promptMetrics(state.prompt,selected.length)}
function updateOverviewStats(){const selected=selectedFeatures();$('#overview-stats').innerHTML=[[FEATURES.length,'capabilities indexed'],[CATEGORIES.length,'architecture domains'],[selected.length,'features selected'],[SYNERGIES.length,'curated fusion patterns']].map(([v,l])=>`<div class="stat"><strong>${v}</strong><span>${l}</span></div>`).join('')}

function renderFusion(selected){
  const head=$('#archetype-matrix thead'),body=$('#archetype-matrix tbody');head.innerHTML=`<tr><th>Archetype</th><th>Fit</th><th>Matched tags</th></tr>`;
  body.innerHTML=ARCHETYPES.map(a=>{const hits=new Set();selected.forEach(f=>f.tags.forEach(t=>{if(a.tags.includes(t))hits.add(t)}));const denom=Math.max(1,a.tags.length),score=Math.min(3,Math.round((hits.size/denom)*3));return `<tr><td>${a.name}</td><td class="score score-${score}">${score}/3</td><td>${[...hits].join(', ')||'—'}</td></tr>`}).join('');
  const names=new Set(selected.map(f=>f.name));const sy=SYNERGIES.filter(s=>s.slice(0,3).filter(n=>names.has(n)).length>=2);$('#synergy-list').innerHTML=sy.length?sy.map(s=>`<div class="synergy"><strong>${s[3]}</strong><div>${s.slice(0,3).map(n=>names.has(n)?`✓ ${escapeHTML(n)}`:`○ ${escapeHTML(n)}`).join(' · ')}</div></div>`).join(''):'<p class="muted">Select more complementary features to reveal curated synergy patterns.</p>';
  $('#selected-cloud').innerHTML=selected.length?selected.map(f=>`<span class="chip" title="${escapeHTML(f.summary)}">${escapeHTML(f.name)} <button data-remove="${f.id}" aria-label="Remove ${escapeHTML(f.name)}">×</button></span>`).join(''):'<span class="muted">No selected features yet.</span>';$$('[data-remove]').forEach(b=>b.onclick=()=>{state.selected.delete(b.dataset.remove);persistSelections();renderFeatures()});
  renderPairMatrix(selected.slice(0,12));
}
function renderPairMatrix(features){const table=$('#pair-matrix');if(!features.length){table.innerHTML='<tr><td>Select features to build a compatibility matrix.</td></tr>';return}const explicit=new Set();for(const s of SYNERGIES){for(const a of s.slice(0,3))for(const b of s.slice(0,3))if(a!==b)explicit.add(`${a}|||${b}`)};table.innerHTML=`<thead><tr><th>Feature</th>${features.map(f=>`<th title="${escapeHTML(f.name)}">${escapeHTML(f.name.slice(0,16))}${f.name.length>16?'…':''}</th>`).join('')}</tr></thead><tbody>${features.map(a=>`<tr><th>${escapeHTML(a.name)}</th>${features.map(b=>{if(a.id===b.id)return'<td>—</td>';const exp=explicit.has(`${a.name}|||${b.name}`),overlap=a.tags.filter(t=>b.tags.includes(t)).length,cls=exp?'pair-strong':overlap?'pair-hit':'';return `<td class="${cls}" title="${exp?'Curated synergy':overlap?`${overlap} shared tags`:'No explicit relation'}">${exp?'◎':overlap?overlap:'·'}</td>`}).join('')}</tr>`).join('')}</tbody>`}

function buildChainOptions(){const el=$('#chain-options');el.innerHTML=CHAIN_STAGES.map(s=>`<label class="stage-check"><input type="checkbox" value="${s.id}" checked><span><strong>${escapeHTML(s.title)}</strong><small>${escapeHTML(s.simple)}</small></span></label>`).join('');renderChainPreview()}
function renderChainPreview(){const ids=$$('#chain-options input:checked').map(x=>x.value);$('#chain-preview').innerHTML=CHAIN_STAGES.filter(s=>ids.includes(s.id)).map((s,i)=>`<div class="timeline-item"><div class="num">${i+1}</div><div><h3>${escapeHTML(s.title)}</h3><p>${escapeHTML(s.simple)}</p><details><summary>Implementation instruction</summary><p>${escapeHTML(s.instruction)}</p></details></div></div>`).join('')}
function generatePrompt(){const opts={selectedFeatures:selectedFeatures(),projectName:$('#project-name').value.trim()||'Feature Fusion Project',goal:$('#project-goal').value.trim(),audience:$('#project-audience').value.trim(),deployment:$('#deployment-target').value,stageIds:$$('#chain-options input:checked').map(x=>x.value)};state.prompt=buildPrompt(opts);$('#prompt-output').value=state.prompt;$('#prompt-metrics').innerHTML=promptMetrics(state.prompt,opts.selectedFeatures.length);setValue('lastPrompt',state.prompt);return state.prompt}
function promptMetrics(text,count){return `<span>${count} features</span><span>${text.length.toLocaleString()} chars</span><span>${text.trim().split(/\s+/).length.toLocaleString()} words</span><span>${$$('#chain-options input:checked').length} stages</span>`}

async function refreshCapabilities(){state.caps=await detectCapabilities();renderCapabilities();const webgpu=state.caps.find(c=>c.id==='webgpu')?.supported;$('#webllm-capability').innerHTML=webgpu?`<span style="color:var(--good)">● WebGPU available</span> · WebLLM ${getWebLLMVersion()} can be loaded on demand.`:`<span style="color:var(--danger)">● WebGPU unavailable</span> · Local WebLLM inference cannot run here; prompt generation still works.`}
function renderCapabilities(){const el=$('#capability-grid');el.innerHTML=state.caps.map(c=>`<div class="cap ${c.supported?'yes':'no'}"><strong>${c.supported?'✓':'×'} ${escapeHTML(c.label)}</strong><small>${escapeHTML(c.note)}</small></div>`).join('');runTests()}
async function runTests(){const tests=await runSelfTests(FEATURES,fs=>buildPrompt({selectedFeatures:fs,goal:'test',audience:'test',deployment:'test'}));$('#test-results').innerHTML=tests.map(t=>`<div class="test"><span>${escapeHTML(t.name)} <small>${escapeHTML(t.detail||'')}</small></span><strong class="${t.pass?'pass':'fail'}">${t.pass?'PASS':'FAIL'}</strong></div>`).join('')}

function renderArchitecture(){const layers=[
 ['User Experience','routes · dashboards · maps · quests · workspaces · guided/expert modes'],['Collaboration','CRDT · presence · chat · boards · docs · deliberation'],['Game & Learning','quests · skills · team XP · mentorship · competency'],['Knowledge & Evidence','graph · citations · datasets · provenance · hybrid search'],['AI & Agents','WebLLM · RAG · tools · meta-prompts · human approval'],['Realtime Transport','WebRTC · Trystero · WebSocket · WebTransport · fallback'],['Coordination','rooms · authority · events · workflows · queues · admission'],['Identity & Trust','passkeys · RBAC/ABAC · object ACLs · moderation'],['Data','SQL · objects · events · search · vectors · cache'],['Local Resilience','IndexedDB · OPFS · PWA · service worker · reconciliation'],['Operations','testing · tracing · diagnostics · security · cost · rollback']
 ];$('#arch-stack').innerHTML=layers.map(([a,b])=>`<div class="arch-layer"><strong>${a}</strong><span>${b}</span></div>`).join('')}

function renderGuides(){const guides=[
 ['Feature fusion','Start with the problem and choose the smallest coherent capability set.','Select features that share objects/events. Define one source of truth per state type. Add fallbacks before decorative features.','Feature fusion is systems design: the value comes from interactions. A quest engine becomes more useful when it consumes verified events; AI becomes safer when it reads provenance-linked evidence; multiplayer becomes durable when transport is separated from synchronization semantics.','Create object schemas → universal event envelope → module contracts → capability/fallback registry → cross-module event map → integration tests.'],
 ['Realtime multiplayer','Choose which interactions truly need realtime behavior.','Use WebRTC for direct peers; WebSocket/room authority for durable coordination; CRDTs for mergeable shared state. Test TURN and reconnect paths.','Networking transport, application synchronization and authority are separate concerns. A direct WebRTC connection does not solve identity, moderation, late joins, persistence or conflict resolution.','Define protocol version, room admission, message schema, snapshot handshake, reconnection/backoff, transport fallback, moderation events and authoritative validations.'],
 ['WebLLM & local AI','Download a compatible model only when the user asks for local AI.','Detect WebGPU, show expected model download clearly, run inference in a Web Worker, preserve a no-AI path, and label outputs as AI-generated.','WebLLM exposes an OpenAI-style interface and worker support. Local inference improves privacy but still consumes significant GPU memory and power. Context quality and tool boundaries matter more than simply adding a model.','Use a provider adapter; stream output; budget context/tokens; optionally enable resumable generation; isolate retrieved content from instructions; record model/version/context provenance.'],
 ['CRDT & local-first sync','Let people edit immediately, then converge safely.','Choose CRDT types around domain semantics; persist local operations; exchange updates; snapshot periodically; test concurrent and offline edits.','CRDTs solve convergence, not business validity. Permission checks, semantic conflicts and destructive operations may still require application rules or an authority service.','Define replica IDs, document boundaries, awareness as ephemeral state, snapshot cadence, tombstone policy, protocol/schema versions and convergence test fixtures.'],
 ['Evidence & provenance','Every important claim should be traceable.','Store source, date, applicability, limitations and review state. Link derived outputs back to transformations and inputs.','A citation is not the same as evidence quality. Provenance should distinguish source material, transformation, model inference, human judgment and measured outcome.','Create evidence/claim/derivation schemas, content hashes, review workflow, stale-source checks, diff history and exportable provenance bundles.'],
 ['Security & moderation','Assume public multiplayer will receive malformed and adversarial input.','Validate network data, sanitize rendering, scope permissions, rate-limit writes, retain rollback history, add report/block/mute and appeals.','P2P encryption does not mean participants are trustworthy. Client-side checks cannot enforce authoritative rules against modified clients. Security boundaries must match threat models.','Threat model → CSP/Trusted Types → schemas → server validation → abuse budgets → moderation audit → recovery/rollback → dependency review.'],
 ['PWA & offline resilience','Keep essential work usable during network failure.','Cache the shell, queue edits, show freshness, never promise uncached APIs offline, and test service-worker upgrades.','A service worker is not a magic offline switch. External CDN modules, live data, identity services and multiplayer still require explicit caching or a fallback.','Version caches, separate immutable/runtime data, migration guard, update UX, queued writes, offline indicator, recovery page and test matrix for first-load-vs-cached behavior.'],
 ['Federation','Let independent communities interoperate without one database owning everything.','Agree on object schemas, identities, signatures, exchange policy and selective replication before building discovery.','Federation moves trust boundaries rather than eliminating them. Each instance needs moderation, retention and federation policies plus mechanisms to verify remote origin.','Instance identity → schema registry → signed messages → allow/deny policy → selective object exchange → federated search → conflict handling.'],
 ['Gamification tied to work','Reward meaningful contribution, learning and verification rather than clicks.','Drive XP from auditable domain events. Add diminishing returns, peer review and no-gamification mode.','Any metric becomes a target. Multidimensional progression and evidence-backed achievements reduce incentives to optimize meaningless activity.','Map events to rewards; define anti-spam caps; distinguish self-report from verified contribution; make team/community progress visible; audit for perverse incentives.'],
 ['Systems & anti-inversion','Check who benefits, who bears risk and what happens when the design fails.','Map stakeholders, unknowns, feedback loops and second-order effects. Run a pre-mortem and classify reversible versus irreversible actions.','High-quality implementation can still optimize the wrong objective. Anti-inversion means the platform keeps human welfare, consent, evidence and contestability visible alongside technical success.','Require review records for consequential actions, missing-stakeholder detector, pre-mortem, reversibility field, assumption registry, outcome monitoring and scheduled reassessment.']
 ];$('#guide-list').innerHTML=guides.map(([title,one,steps,adv,impl])=>`<details class="guide"><summary>${escapeHTML(title)}</summary><div class="guide-body"><div class="depth"><h3>One-minute explanation</h3><p>${escapeHTML(one)}</p></div><div class="depth"><h3>Actionable steps</h3><p>${escapeHTML(steps)}</p></div><div class="depth"><h3>Advanced explanation</h3><p>${escapeHTML(adv)}</p></div><div class="depth"><h3>Implementation detail</h3><p>${escapeHTML(impl)}</p></div></div></details>`).join('')}

async function updateStatePreview(){const s=await getAllState();const est=await storageEstimate();$('#state-preview').textContent=JSON.stringify({storedKeys:Object.keys(s),selectedFeatures:state.selected.size,theme:state.theme,storageEstimate:est?{usage:est.usage,quota:est.quota}:null,online:navigator.onLine,webLLM:engineInfo(),p2pJoined:isJoined()},null,2)}
function updateConnectivity(){const on=navigator.onLine;$('#online-label').textContent=on?'Online':'Offline';$('#online-dot').className='dot '+(on?'good':'bad')}
function drawConstellation(){const el=$('#constellation');let html='';const pts=[];for(let i=0;i<16;i++){const x=10+Math.random()*80,y=10+Math.random()*80;pts.push([x,y]);html+=`<i style="left:${x}%;top:${y}%;transform:scale(${.6+Math.random()})"></i>`}for(let i=0;i<10;i++){const [x1,y1]=pts[i],[x2,y2]=pts[(i+3)%pts.length],dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy),angle=Math.atan2(dy,dx)*180/Math.PI;html+=`<b style="left:${x1}%;top:${y1}%;width:${len}%;transform:rotate(${angle}deg)"></b>`}el.innerHTML=html}

async function exportWorkspace(){const data={schema:'feature-fusion-foundry.workspace',version:1,exportedAt:new Date().toISOString(),selectedFeatures:[...state.selected],project:{name:$('#project-name').value,goal:$('#project-goal').value,audience:$('#project-audience').value,deployment:$('#deployment-target').value},prompt:$('#prompt-output').value,settings:{theme:state.theme,reduceMotion:state.reduceMotion}};download(`feature-fusion-workspace-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(data,null,2),'application/json');toast('Workspace exported')}
async function importWorkspace(file){const data=JSON.parse(await file.text());if(data.schema!=='feature-fusion-foundry.workspace'||data.version!==1)throw new Error('Unsupported workspace schema/version');state.selected=new Set((data.selectedFeatures||[]).filter(id=>FEATURES.some(f=>f.id===id)));if(data.project){$('#project-name').value=data.project.name||'';$('#project-goal').value=data.project.goal||'';$('#project-audience').value=data.project.audience||'';if([...$('#deployment-target').options].some(o=>o.value===data.project.deployment))$('#deployment-target').value=data.project.deployment}$('#prompt-output').value=data.prompt||'';state.prompt=data.prompt||'';await setValue('selectedFeatures',[...state.selected]);renderFeatures();renderSelectedDependent();toast('Workspace imported')}

async function hashSelectedFile(){const file=$('#hash-file').files[0];if(!file){toast('Choose a file first');return}const digest=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());const hex=[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');$('#hash-output').textContent=`${file.name}\nSHA-256 ${hex}`}

async function setupWebLLM(){try{$('#load-models').disabled=true;$('#model-status').textContent='Loading WebLLM module and model catalog…';const models=await loadCatalog();const select=$('#webllm-model');select.innerHTML=models.map(m=>`<option value="${escapeHTML(m.id)}">${escapeHTML(m.label)}</option>`).join('');const idx=models.findIndex(m=>/360M|0\.5B|1B|Smol/i.test(m.id));if(idx>=0)select.selectedIndex=idx;$('#load-webllm').disabled=!navigator.gpu;$('#model-status').textContent=`Catalog ready: ${models.length} models. Choose one and load it explicitly.`}catch(e){$('#model-status').textContent=`Catalog error: ${e.message}`}finally{$('#load-models').disabled=false}}
async function loadSelectedModel(){const id=$('#webllm-model').value;if(!id)return;$('#load-webllm').disabled=true;$('#model-status').textContent=`Loading ${id}…`;try{await initEngine(id,p=>{const frac=Math.max(0,Math.min(1,p.progress??0));$('#model-progress').style.width=(frac*100)+'%';$('#model-status').textContent=p.text||`Loading ${(frac*100).toFixed(1)}%`});$('#run-ai').disabled=false;$('#unload-webllm').disabled=false;$('#model-status').textContent=`Ready: ${id}`;toast('Local model ready')}catch(e){$('#model-status').textContent=`Model load failed: ${e.message}`}finally{$('#load-webllm').disabled=false}}
async function runLocalAI(){const base=$('#prompt-output').value.trim()||generatePrompt();const mode=$('#ai-mode').value,instruction=$('#ai-instruction').value,resumable=$('#resumable-ai').checked;$('#run-ai').disabled=true;$('#stop-ai').disabled=false;$('#ai-output').textContent='';try{if(mode!=='three'){await generate({prompt:stagePrompt(mode,base,instruction),resumable,onToken:(_,full)=>$('#ai-output').textContent=full});}else{const stages=[['fusion','ARCHITECT'],['redteam','RED-TEAM'],['critic','INTEGRATOR']];let current=base,all='';for(const [m,label] of stages){all+=`\n\n===== ${label} =====\n`;$('#ai-output').textContent=all;const result=await generate({prompt:stagePrompt(m,current,instruction),resumable,onToken:(_,full)=>$('#ai-output').textContent=all+full,maxTokens:900});all+=result.text;current=result.text}$('#ai-output').textContent=all;}toast('Local AI chain complete')}catch(e){if(e.name==='AbortError')toast('Generation stopped');else{$('#ai-output').textContent+=`\n\n[Error] ${e.message}`;toast('AI generation error')}}finally{$('#run-ai').disabled=false;$('#stop-ai').disabled=true}}

async function joinRoom(){const id=$('#room-id').value.trim(),password=$('#room-password').value;if(!id){toast('Enter a room ID');return}$('#join-room').disabled=true;$('#room-status').textContent='Connecting…';try{const info=await joinP2PRoom({roomId:id,password,onPeerJoin:peer=>{state.peers.add(peer);renderPeers();logRoom(`Peer joined: ${peer.slice(0,10)}…`,true)},onPeerLeave:peer=>{state.peers.delete(peer);renderPeers();logRoom(`Peer left: ${peer.slice(0,10)}…`,true)},onMessage:data=>logRoom(data.system?data.text:`${data.name||data.peerId?.slice(0,8)||'Peer'}: ${data.text}`,!!data.system)});$('#room-status').textContent=`Joined “${id}” · self ${info.selfId.slice(0,10)}… · Trystero ${info.version}`;$('#leave-room').disabled=false;$('#send-room').disabled=false;logRoom('Joined decentralized room. Open the same deployed page in another browser/device to test peer messaging.',true)}catch(e){$('#room-status').textContent=`Connection failed: ${e.message}`;$('#join-room').disabled=false}}
function leaveRoom(){leaveP2PRoom();state.peers.clear();renderPeers();$('#join-room').disabled=false;$('#leave-room').disabled=true;$('#send-room').disabled=true;$('#room-status').textContent='Not connected.';logRoom('Left room.',true)}
function renderPeers(){$('#peer-list').innerHTML=state.peers.size?[...state.peers].map(p=>`<span class="chip">peer ${escapeHTML(p.slice(0,8))}</span>`).join(''):'<span class="muted">No remote peers yet.</span>'}
function logRoom(text,system=false){const d=document.createElement('div');d.className='chat-msg';d.innerHTML=`<small>${new Date().toLocaleTimeString()}${system?' · system':''}</small><div>${escapeHTML(text)}</div>`;$('#room-log').append(d);$('#room-log').scrollTop=$('#room-log').scrollHeight}
function sendRoom(){const text=$('#room-message').value.trim();if(!text)return;const name=$('#display-name').value.trim()||'Explorer';try{sendP2P({name,text,ts:Date.now()});logRoom(`${name} (you): ${text}`);$('#room-message').value=''}catch(e){toast(e.message)}}

function globalSearch(q){q=q.trim().toLowerCase();if(!q){$('#global-results').innerHTML='';return}const routeHits=ROUTES.filter(r=>r[1].toLowerCase().includes(q)).map(r=>({href:'#'+r[0],name:r[1],detail:'Workspace route'}));const featureHits=FEATURES.filter(f=>[f.name,f.summary,f.categoryTitle,...f.tags].join(' ').toLowerCase().includes(q)).slice(0,18).map(f=>({href:'#library',name:f.name,detail:f.summary,feature:f.id}));$('#global-results').innerHTML=[...routeHits,...featureHits].map(h=>`<a class="global-hit" href="${h.href}" ${h.feature?`data-global-feature="${h.feature}"`:''}><strong>${escapeHTML(h.name)}</strong><small>${escapeHTML(h.detail)}</small></a>`).join('')||'<p>No matches.</p>';$$('[data-global-feature]').forEach(a=>a.onclick=()=>{$('#feature-search').value=FEATURES.find(f=>f.id===a.dataset.globalFeature)?.name||'';renderFeatures();closeSearch()});$$('#global-results a:not([data-global-feature])').forEach(a=>a.onclick=closeSearch)}
function openSearch(){$('#search-modal').hidden=false;setTimeout(()=>$('#global-search').focus(),10)}function closeSearch(){$('#search-modal').hidden=true}

function bindEvents(){
  ['feature-search','category-filter','maturity-filter','selected-only'].forEach(id=>$('#'+id).addEventListener('input',renderFeatures));
  $('#select-visible').onclick=()=>{FEATURES.filter(featureMatches).forEach(f=>state.selected.add(f.id));persistSelections();renderFeatures()};$('#clear-selected').onclick=()=>{state.selected.clear();persistSelections();renderFeatures()};
  $$('.preset').forEach(b=>b.onclick=()=>{const names=PRESETS[b.dataset.preset]||[];state.selected.clear();names.forEach(n=>{const f=featureByName(n);if(f)state.selected.add(f.id)});persistSelections();renderFeatures();toast(`${b.textContent} preset applied`)});
  $$('#chain-options input').forEach(x=>x.onchange=renderChainPreview);$('#generate-prompt').onclick=()=>{generatePrompt();toast('Fusion prompt generated')};$('#copy-prompt').onclick=async()=>{const text=$('#prompt-output').value||generatePrompt();await navigator.clipboard.writeText(text);toast('Prompt copied')};$('#download-prompt').onclick=()=>download('feature-fusion-build-prompt.md',$('#prompt-output').value||generatePrompt(),'text/markdown');
  $('#theme-toggle').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;localStorage.setItem('fusion-theme',state.theme);setValue('theme',state.theme)};$('#motion-toggle').onclick=()=>{state.reduceMotion=!state.reduceMotion;document.documentElement.classList.toggle('reduce-motion',state.reduceMotion);setValue('reduceMotion',state.reduceMotion);toast(`Motion ${state.reduceMotion?'reduced':'enabled'}`)};
  $('#drawer-toggle').onclick=()=>{const open=$('#side').classList.toggle('open');$('#drawer-toggle').setAttribute('aria-expanded',String(open))};document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#side').classList.remove('open');closeSearch()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}});
  $('#export-state').onclick=exportWorkspace;$('#import-state').onchange=async e=>{try{if(e.target.files[0])await importWorkspace(e.target.files[0])}catch(err){toast(`Import failed: ${err.message}`)}e.target.value=''};
  $('#hash-button').onclick=hashSelectedFile;$('#rerun-tests').onclick=refreshCapabilities;
  $('#load-models').onclick=setupWebLLM;$('#load-webllm').onclick=loadSelectedModel;$('#unload-webllm').onclick=async()=>{await unloadEngine();$('#run-ai').disabled=true;$('#unload-webllm').disabled=true;$('#model-progress').style.width='0';$('#model-status').textContent='Engine unloaded.'};$('#run-ai').onclick=runLocalAI;$('#stop-ai').onclick=stopGeneration;
  $('#join-room').onclick=joinRoom;$('#leave-room').onclick=leaveRoom;$('#send-room').onclick=sendRoom;$('#room-message').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey))sendRoom()});
  $('#global-search-button').onclick=openSearch;$('#search-close').onclick=closeSearch;$('#search-modal').onclick=e=>{if(e.target===$('#search-modal'))closeSearch()};$('#global-search').oninput=e=>globalSearch(e.target.value);
  window.addEventListener('beforeunload',()=>{try{leaveP2PRoom()}catch{}});
}

init().catch(err=>{console.error(err);document.body.insertAdjacentHTML('afterbegin',`<div class="noscript">Startup error: ${escapeHTML(err.message)}</div>`)})
